buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
    }
}

apply plugin: 'com.android.library'

repositories {
    google()
    mavenCentral()
}

android {
    compileSdk 36
    namespace 'org.godotengine.plugin.android.mediapipepose'
    
    defaultConfig {
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    compileOnly 'org.godotengine:godot:4.3.0.stable'
    implementation 'com.google.mediapipe:tasks-vision:0.10.14'
}
